# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.donnyelectric.com
title: Donny Electric
# email: your-email@domain.com
description: > # 
"Donny Electric is a full service electrician serving Southern California. 
Services available for residential and commercial clients."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: 
  - title: github
    url: 
  - title: linkedin
    url: 
